### ISSUE TITLE
未看到StarRocks的demo

### ISSUE THREAD

**Issue by justforsoy** [Tencent/fast-causal-inference#1]
感谢开源，但是看介绍中提到：
“Based on the vectorized OLAP execution engine ClickHouse/StarRocks, the speed is more conducive to the ultimate user experience”
但实际demo中只看到clickhouse的配置，请问现在是否已经支持StarRocks，能否补上demo

**Comment by mlimwxxnn** [comment]
StarRocks的部分demo在开发中，后续会加进来

**Comment by justforsoy** [comment]
> StarRocks的部分demo在开发中，后续会加进来

未看到更新，方便透露下计划和进展么
