### ISSUE TITLE
需要StarRock的支持

### ISSUE THREAD

**Issue by justforsoy** [Tencent/fast-causal-inference#3]
StarRocks的部分demo在开发中，后续会加进来

_Originally posted by @mlimwxxnn in https://github.com/Tencent/fast-causal-inference/issues/1#issuecomment-1729343564_
            

未看到更新，方便透露下计划和进展么

**Comment by huangyanyanyan** [comment]
hi, justforsoy, We plan to offer a range of Starrocks basic operators by the end of December 23, Stay tuned

**Comment by humingxu** [comment]
期待期待 我们也有在starrocks中使用的场景
